### PR TITLE
Fix get_loader returning None when load_jupyter_server_extension is not found (#1193)Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

### PR DESCRIPTION
**Pull request by cmd-ntrf**
## Description

The function `extension.utils.get_loader` returns `None` instead of raising an exception when an extension does not define`_load_jupyter_server_extension` nor `load_jupyter_server_extension`.

## Reproduce

1. Install an extension that does not define `load_jupyter_server_extension` nor `_load_jupyter_server_extension`, for example [jupyterlab-nvdashboard](https://github.com/rapidsai/jupyterlab-nvdashboard)
2. Launch jupyter lab
The following exception appears in the log:
```
     Traceback (most recent call last):
      File "/opt/jupyterhub/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 355, in load_extension
        extension.load_all_points(self.serverapp)
      File "/opt/jupyterhub/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 229, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/jupyterhub/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 229, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/jupyterhub/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 222, in load_point
        return point.load(serverapp)
      File "/opt/jupyterhub/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 148, in load
        return loader(serverapp)
    TypeError: 'NoneType' object is not callable
```

## Expected behavior

The user should get an AttributeError exception instead of a TypeError, making it clear that `_load_jupyter_server_extension` is missing for the extension being loaded.

## Context

The problem was introduced by PR #742, when a default value of `None` was configured if `gettattr` could not find `load_jupyter_server_extension`. The change was made to satisfy Flake8.

## Fix implemented in this PR

Remove the default value for `gettatr` in get_loader and set the comment `# noqa B009` to keep Flake8 satisfied.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks @cmd-ntrf!  It looks like one test needs to be updated:

```
=========================== short test summary info ============================
FAILED tests/extension/test_utils.py::test_get_loader - AttributeError: 'object' object has no attribute 'load_jupyter_server_extension'
```

**Comment by cmd-ntrf** [comment]
While fixing the tests, I realized `get_loader` would never raised `ExtensionLoadingError`, so I splitted the try/except in two. I have also added a test that a deprecated warning was raised, instead of ignoring the warning. Finally, the test for when the module is missing both possible function name now correctly validates that an `ExtensionLoadingError` is raised.

**Comment by blink1073** [comment]
The link failure is unrelated but the lint failure is: `tests/extension/test_utils.py:2:8: F401 `warnings` imported but unused`.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by cmd-ntrf** [comment]
I originally stumbled on this issue while using jupyter-server 1.23.5, so this patch should probably be backported to 1.x.

**Comment by blink1073** [comment]
@meeseeksdev please backport to 1.x
